#!/usr/bin/env bash
apt update
apt install -y nginx
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
string="server_name aydentownsley.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default
service nginx restart
