#!/usr/bin/env bash
#fixing nginx
sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::]:8080 default_server ipv6only=on;/listen \[::]:80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
