#!/usr/bin/env bash
# This script prints using while loop, then prints withing using if
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
