#!/usr/bin/env bash
# This script prints using while loop, then prints withing using case
i=1
while [ $i -le 20 ]
do
	case $i in
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
	esac
	echo $i
	i=$(( i + 1 ))
done
