#!/usr/bin/env bash
# checks for info on file
FILE=holbertonschool
if [[ -e $FILE ]]
then
	echo "$FILE file exists"
	if [[ -s $FILE ]]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi

	if [[ -f $FILE ]]
	then
		echo "$FILE is a regular file"
	else
		:
	fi
else
	echo "$FILE file does not exist"

fi