#!/usr/bin/env bash
# setting up nginx with gunicorn
string="server_name _;\n\tlocation \/airbnb-onepage\/ {\n\t\tproxy_pass http://127.0.0.1:5000;\n\t}\n\n"
sed -i "s|server_name _;|$string|" /etc/nginx/sites-available/default
service nginx restart
reboot
